CREATE DATABASE servos;

CREATE TABLE stations (
    id SERIAL PRIMARY KEY,
    OBJECTID INT,
    FEATURETYPE TEXT,
    DESCRIPTION TEXT,
    CLASS TEXT,
    FID INT,
    NAME TEXT,
    OPERATIONALSTATUS TEXT,
    OWNER TEXT,
    INDUSTRYID INT,
    ADDRESS TEXT,
    SUBURB TEXT,
    STATE TEXT,
    SPATIALCONFIDENCE TEXT,
    REVISED TEXT,
    COMMENT TEXT,
    LATITUDE DOUBLE PRECISION,
    LONGITUDE DOUBLE PRECISION
);


COPY stations(OBJECTID, FEATURETYPE, DESCRIPTION, CLASS, FID, NAME, OPERATIONALSTATUS, OWNER, INDUSTRYID, ADDRESS, SUBURB, STATE, SPATIALCONFIDENCE, REVISED, COMMENT, LATITUDE, LONGITUDE) FROM '/Users/christianleong/sei/pipeline/db/stations.csv' WITH CSV HEADER;

ALTER TABLE stations 
DROP COLUMN OBJECTID,
DROP COLUMN FEATURETYPE,
DROP COLUMN DESCRIPTION,
DROP COLUMN CLASS,
DROP COLUMN FID,
DROP COLUMN INDUSTRYID,
DROP COLUMN REVISED,
DROP COLUMN COMMENT;

SELECT *
FROM stations
LIMIT 2;